### PR TITLE
Python 3 friendly print

### PR DESCRIPTION
**Pull request by tkeffer**
Python 3 incompatibilities are creeping in again.

I was able to get this version to work.

### CODE REVIEW

**Comment by tkeffer** [comment]
You may or may not want to add this second commit. It makes it easier to switch between GET and POST.

**Comment by matthewwall** [comment]
is this code actually working for you using POST?

windy still won't issue me a station identifier/key.  at first i thought because i'm hitting it from korea, but even when i vpn then hit it from a us address i still get no joy.  makes it rather tedious to test.

i need to get rid of those dirty python2 habits :)

**Comment by tkeffer** [comment]
I got an API key. You want me to try and get one for you?

As far as I can tell, it works when using GET, but I keep getting `404` errors when I try POST.

**Comment by tkeffer** [comment]
Out of date. Closed

**Pull request closed without merging**
